language: node_js
node_js:
  - '10.8'

addons:
  apt:
    packages:
      - libgconf-2-4 # Required to run Cypress

cache:
  directories:
    - build # shows bundle size diff per file/chunk
    - '$HOME/.cache/Cypress' # for caching the (rather large) Cypress binary

before_install: npm install -g greenkeeper-lockfile@1

install: npm ci --loglevel http

before_script: greenkeeper-lockfile-update

# Example Cypress Travis-CI config found here:
# https://github.com/cypress-io/cypress-example-kitchensink/blob/master/.travis.yml
jobs:
  include:
    - stage: test-and-build
      name: 'Unit Testing'
      script: npm run test-ci
    # Running Cypress tests in parallel by running them in batches
    # This could probably be improved by writing a Node script to handle a config
    - stage: test-and-build
      name: 'Integration Testing - Accounts, Events, Navigation'
      env: SPECS='cypress/tests/integration/accounts/**/*,cypress/tests/integration/events/**/*,cypress/tests/integration/navigation/**/*'
      script: npm run test-integration-ci
    - stage: test-and-build
      name: 'Integration Testing - Templates, Recipient Validation'
      env: SPECS='cypress/tests/integration/templates/**/*,cypress/tests/integration/recipient-validation/**/*'
      script: npm run test-integration-ci

after_script: greenkeeper-lockfile-upload
